### ISSUE TITLE
Is support for Swift 3.0.2 planned?

### ISSUE THREAD

**Issue by serieuxchat** [svdo/swift-SecurityExtensions#2]
Currently it does not compile for Swift 3.0.2. Is an updated planned for this?

**Comment by svdo** [comment]
Can you please elaborate? I just verified that compilation and unit tests are working normally on my machine. What issue are you seeing? Which Xcode version are you using?

**Comment by svdo** [comment]
Thanks for bringing this to my attention. In fact the code was already migrated to swift3, but not yet released. I'll make a new version.

**Comment by svdo** [comment]
Just released version 3.0.0 (https://cocoapods.org/pods/SecurityExtensions).

**Comment by svdo** [comment]
By the way: I just noticed your comment on IDZSwiftCommonCrypto about minimum deployment target. I'm downloading 9.0 simulator and will release update if it also works there.

**Comment by serieuxchat** [comment]
Sorry. The original error was, indeed, related to the minimum deployment target of IDZSwiftCommonCrypto. I copied and tweaked their podspec to test if it worked with the lower number, but some derived data remnant was messing things up.

**Comment by serieuxchat** [comment]
Thanks very much for replying/addressing it so fast!

**Comment by svdo** [comment]
Released 3.0.1. Hope it works now!
